// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uEWT1C6ySrjtSMWJntBego
// Component: 8lN_knEESkxt
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MainHeader from "../../MainHeader"; // plasmic-import: wtnE0On9QToy/component
import Button2 from "../../Button2"; // plasmic-import: 48nEEeCzck2s/component
import { Anchor } from "../../registerAnchor"; // plasmic-import: ONinya1RhOT2/codeComponent
import { AntdAccordion } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { accordionHelpers as AntdAccordion_Helpers } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { AntdAccordionItem } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import Footer from "../../Footer"; // plasmic-import: Iz_Y_kKZMHTD/component
import { useScreenVariants as useScreenVariantsraGa2MJbEFd } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: RaGa2M-JbEFd/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic.module.css"; // plasmic-import: uEWT1C6ySrjtSMWJntBego/projectcss
import sty from "./PlasmicRecorridoCamaraDeComercioDeGuadalajara.module.css"; // plasmic-import: 8lN_knEESkxt/css

createPlasmicElementProxy;

export const PlasmicRecorridoCamaraDeComercioDeGuadalajara__VariantProps =
  new Array();

export const PlasmicRecorridoCamaraDeComercioDeGuadalajara__ArgProps =
  new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRecorridoCamaraDeComercioDeGuadalajara__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "accordion.activePanelId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "2",
        onMutate: generateOnMutateForSpec(
          "activePanelId",
          AntdAccordion_Helpers
        )
      },
      {
        path: "mainHeader.menuOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsraGa2MJbEFd()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicRecorridoCamaraDeComercioDeGuadalajara.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={
            PlasmicRecorridoCamaraDeComercioDeGuadalajara.pageMetadata.title
          }
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={
            PlasmicRecorridoCamaraDeComercioDeGuadalajara.pageMetadata.title
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainSection"}
          data-plasmic-override={overrides.mainSection}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.mainSection
          )}
        >
          <MainHeader
            data-plasmic-name={"mainHeader"}
            data-plasmic-override={overrides.mainHeader}
            className={classNames("__wab_instance", sty.mainHeader)}
            menuOpen={generateStateValueProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
            onMenuOpenChange={generateStateOnChangeProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
          />

          <div
            data-plasmic-name={"mainBanner"}
            data-plasmic-override={overrides.mainBanner}
            className={classNames(projectcss.all, sty.mainBanner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"banner"}
              data-plasmic-override={overrides.banner}
              hasGap={true}
              className={classNames(projectcss.all, sty.banner)}
            />
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"description"}
            data-plasmic-override={overrides.description}
            hasGap={true}
            className={classNames(projectcss.all, sty.description)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__nJAgA)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jyD2E
                )}
              >
                {"Recorridos\nC\u00e1mara de Comercio de Guadalajara"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uesNl
                )}
              >
                {
                  "\u201cLa ruta del tequila en colaboraci\u00f3n con Casa Sauza, donde la cultura y la gastronom\u00eda se entrelazan.\u201d"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__noqZy
                )}
              >
                {
                  "Explora Tequila junto con la C\u00e1mara de Comercio de Guadalajara, una instituci\u00f3n con m\u00e1s de 135 a\u00f1os de historia impulsando el desarrollo econ\u00f3mico y social de la regi\u00f3n.\n\nEste emblem\u00e1tico recorrido te permitir\u00e1 adentrarte en el coraz\u00f3n y la historia del tequila con un viaje a trav\u00e9s de los pintorescos campos de agave. Disfruta la m\u00e1s exquisita cocteler\u00eda y la gastronom\u00eda local, acompa\u00f1ado de un espect\u00e1culo art\u00edstico que captura la esencia de M\u00e9xico y sus tradiciones."
                }
              </div>
              <Button2
                className={classNames("__wab_instance", sty.button2__htEo1)}
                label={"Reservar"}
              />
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tO2FH)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__mM6Z7)} />
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zclbr)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8UEOa
                  )}
                >
                  {"Todos los s\u00e1bados."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8JEla
                  )}
                >
                  {"7:00 - 19:45 / Tren GDL-TQL-GDL con experiencia"}
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"divider"}
            data-plasmic-override={overrides.divider}
            hasGap={true}
            className={classNames(projectcss.all, sty.divider)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__sbmwB)} />
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"meta"}
            data-plasmic-override={overrides.meta}
            hasGap={true}
            className={classNames(projectcss.all, sty.meta)}
          >
            <Anchor
              data-plasmic-name={"anchor"}
              data-plasmic-override={overrides.anchor}
              className={classNames("__wab_instance", sty.anchor)}
              items={[
                { key: "salidas", href: "#salidas", title: "Salidas" },
                { key: "paquetes", href: "#paquetes", title: "Paquetes" },
                {
                  key: "encuentro",
                  href: "#encuentro",
                  title: "Punto de Encuentro"
                },
                {
                  key: "que-llevar",
                  href: "#que-llevar",
                  title: "Qu\u00e9 Llevar"
                },
                {
                  key: "consideraciones",
                  href: "#consideraciones",
                  title: "Consideraciones"
                },
                { key: "reservar", href: "#reservar", title: "Reservar" }
              ]}
              offsetTop={75}
              targetOffset={500}
            />

            <div className={classNames(projectcss.all, sty.freeBox__pN69)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pK7Kn
                )}
              >
                {"Informaci\u00f3n"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zzcgb)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__xafW8)}
                  displayHeight={"54px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"54px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tequila_express/images/group82Jpg.jpg",
                    fullWidth: 108,
                    fullHeight: 108,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__acOlW)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kfC7G
                    )}
                  >
                    {"Operado por C\u00e1mara de Comercio de Guadalajara"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h18GL
                    )}
                  >
                    {
                      "Elige entre dos categor\u00edas que te permitir\u00e1n sumergirte en la rica herencia de Tequila con un nivel \u00fanico de estilo."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <div
                className={classNames(projectcss.all, sty.freeBox__hdLoz)}
                id={"salidas"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g2Jw
                  )}
                >
                  {"Salidas"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__avYjZ)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__thhzv
                  )}
                >
                  {"Todos los s\u00e1bados."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e4S
                  )}
                >
                  {
                    "Itinerario:\n7:00 - 19:45 / Tren GDL-TQL-GDL con experiencia"
                  }
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__d55F)}
                id={"paquetes"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jZuu3
                  )}
                >
                  {"Paquetes"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__yXipv)}
                />

                {(() => {
                  const child$Props = {
                    activeKey: generateStateValueProp($state, [
                      "accordion",
                      "activePanelId"
                    ]),
                    bordered: true,
                    className: classNames("__wab_instance", sty.accordion),
                    defaultActiveKey: "2",
                    ghost: true,
                    items: (
                      <React.Fragment>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem___8JBds
                          )}
                          id={1}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mcXk
                              )}
                            >
                              {"Clase Ejecutiva"}
                            </div>
                          }
                          showArrow={false}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__k1UgP
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__mJCat)}
                              displayHeight={"375px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"40%"}
                              displayWidth={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "100%"
                                  : "40%"
                              }
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/tequila_express/images/rectangle70Jpg.jpg",
                                fullWidth: 846,
                                fullHeight: 756,
                                aspectRatio: undefined
                              }}
                            />

                            <Stack__
                              as={"div"}
                              data-plasmic-name={"title2"}
                              data-plasmic-override={overrides.title2}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.title2)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__wLyVx
                                )}
                              >
                                {"Viaje Sencillo"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__cCGmX
                                )}
                              >
                                {hasVariant(globalVariants, "screen", "medium")
                                  ? "$XXX.00 MXN"
                                  : "$XXX.00 MXN"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__vki91
                                )}
                              >
                                <React.Fragment>
                                  <React.Fragment>
                                    {
                                      "La mayor comodidad para viajar con gran espacio entre asientos y una disposici\u00f3n que favorece la convivencia.\n"
                                    }
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__l9Elc
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__xqsd0
                                        )}
                                      >
                                        {"Vag\u00f3n Bar"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__xRQxN
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__n3BnX
                                        )}
                                      >
                                        {"Ventanas panor\u00e1micas"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__s74K8
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__osJjh
                                        )}
                                      >
                                        {"60 asientos"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul___3ZH5J
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__ohwy9
                                        )}
                                      >
                                        {"2 ba\u00f1os\n"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>
                                    {"\nIncluye:\n"}
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul___3Nmuk
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__ndvNw
                                        )}
                                      >
                                        {
                                          "Espacio para almacenar una maleta de mano (medidas)\u2026"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__gmeww
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__iz8W
                                        )}
                                      >
                                        {
                                          "Traslado en cami\u00f3n Estaci\u00f3n Tequila - Tequila Centro (ida y vuelta)"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__iq4D8
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___35Odk
                                        )}
                                      >
                                        {"Seguro de viaje en el transporte"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                </React.Fragment>
                              </div>
                            </Stack__>
                          </Stack__>
                        </AntdAccordionItem>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem__tTjAo
                          )}
                          id={"2"}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___7OkY
                              )}
                            >
                              {"Primera Clase"}
                            </div>
                          }
                          showArrow={false}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___09St0
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__mHsoZ)}
                              displayHeight={"375px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"40%"}
                              displayWidth={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "100%"
                                  : "40%"
                              }
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/tequila_express/images/rectangle70Jpg2.jpg",
                                fullWidth: 846,
                                fullHeight: 756,
                                aspectRatio: undefined
                              }}
                            />

                            <Stack__
                              as={"div"}
                              data-plasmic-name={"title3"}
                              data-plasmic-override={overrides.title3}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.title3)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__fzhSw
                                )}
                              >
                                {"Viaje Sencillo"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__hNpvi
                                )}
                              >
                                {hasVariant(globalVariants, "screen", "medium")
                                  ? "$XXX.00 MXN"
                                  : "$XXX.00 MXN"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__pDb
                                )}
                              >
                                <React.Fragment>
                                  <React.Fragment>
                                    {
                                      "La mayor comodidad para viajar con gran espacio entre asientos y una disposici\u00f3n que favorece la convivencia.\n"
                                    }
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__o73F0
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___5ETbt
                                        )}
                                      >
                                        {"Vag\u00f3n Bar"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__vCje8
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__hveg6
                                        )}
                                      >
                                        {"Ventanas panor\u00e1micas"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__xBi8P
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___47MyC
                                        )}
                                      >
                                        {"60 asientos"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul___6WCxl
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__xciPh
                                        )}
                                      >
                                        {"2 ba\u00f1os\n"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>
                                    {"\nIncluye:\n"}
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__zunY
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__mnPr5
                                        )}
                                      >
                                        {
                                          "Espacio para almacenar una maleta de mano (medidas)\u2026"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__bYk8V
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__zVxQi
                                        )}
                                      >
                                        {
                                          "Traslado en cami\u00f3n Estaci\u00f3n Tequila - Tequila Centro (ida y vuelta)"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__iTcPo
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__zn9EE
                                        )}
                                      >
                                        {"Seguro de viaje en el transporte"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                </React.Fragment>
                              </div>
                            </Stack__>
                          </Stack__>
                        </AntdAccordionItem>
                      </React.Fragment>
                    ),

                    onChange: generateStateOnChangePropForCodeComponents(
                      $state,
                      "activePanelId",
                      ["accordion", "activePanelId"],
                      AntdAccordion_Helpers
                    )
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "activePanelId",
                        plasmicStateName: "accordion.activePanelId"
                      }
                    ],

                    [],
                    AntdAccordion_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <AntdAccordion
                      data-plasmic-name={"accordion"}
                      data-plasmic-override={overrides.accordion}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__z5Vkv)}
                id={"encuentro"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e48Ua
                  )}
                >
                  {"Punto de Encuentro"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__hYw0)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iFy8N)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hwAy7)}
                    displayHeight={"300px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : hasVariant(globalVariants, "screen", "tablet")
                        ? "100%"
                        : "40%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tequila_express/images/imageJpg2.jpg",
                      fullWidth: 1224,
                      fullHeight: 504,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__cw9SQ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yot5Z
                      )}
                    >
                      {"C\u00e1mara de Comercio de Guadalajara"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h3EO
                      )}
                    >
                      {"Direcci\u00f3n"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__n84ZA
                      )}
                    >
                      {
                        "Av. Ignacio L Vallarta 4085\nCamino Real\n45040\nZapopan, Jal."
                      }
                    </div>
                  </div>
                </Stack__>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__v21RY)}
                id={"que-llevar"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3M9C
                  )}
                >
                  {"Qu\u00e9 Llevar"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__apr8V)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e6IJr
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__vHhb3
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__ivrik
                          )}
                        >
                          {"Identificaci\u00f3n oficial"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__e5CKf
                          )}
                        >
                          {"Copia de correo de confirmaci\u00f3n"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__rdinq
                          )}
                        >
                          {"Zapato cerrado y c\u00f3modo"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__mwpxk
                          )}
                        >
                          {"Lentes de sol y sombrero"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__pNdQd
                          )}
                        >
                          {"Ropa c\u00f3moda"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__fFbU
                          )}
                        >
                          {"Protector solar"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__op3T)}
                id={"consideraciones"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wkKV
                  )}
                >
                  {"Consideraciones"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5HkS)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sFtAs
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__rdfGg
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___5Qivr
                          )}
                        >
                          {
                            "El Vag\u00f3n Bar es exclusivamente para mayores de edad"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___8KlvP
                          )}
                        >
                          {
                            "El viaje en Vag\u00f3n Ejecutivo est\u00e1 disponible para ni\u00f1os a partir de 6 a\u00f1os"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__eumF9
                          )}
                        >
                          {
                            "Presentarse con una hora de anticipaci\u00f3n para su registro"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__iFrH
                          )}
                        >
                          {"Itinerarios sujetos a cambios"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__xgFf
                          )}
                        >
                          {
                            "Los tiempos de traslados del tren y autob\u00fas son aproximados y sujetos a situaciones ajenas a la empresa"
                          }
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__tC2Rt)}
                id={"reservar"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xpZxz)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mz93Y)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jph3A
                      )}
                    >
                      {"Inicia el viaje"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__brDz3
                      )}
                    >
                      {
                        "Tequila Express re\u00fane los itinerarios y la oferta diferenciada de los diversos operadores por la ruta del tequila. Al presionar reservar ser\u00e1s redirigido al sitio oficial del operador para completar tu reserva."
                      }
                    </div>
                  </div>
                  <Button2
                    className={classNames("__wab_instance", sty.button2__lmWa4)}
                    label={"Reservar"}
                    light={true}
                  />
                </Stack__>
              </div>
            </div>
          </Stack__>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  mainSection: [
    "mainSection",
    "mainHeader",
    "mainBanner",
    "banner",
    "description",
    "divider",
    "meta",
    "anchor",
    "accordion",
    "title2",
    "title3",
    "footer"
  ],

  mainHeader: ["mainHeader"],
  mainBanner: ["mainBanner", "banner"],
  banner: ["banner"],
  description: ["description"],
  divider: ["divider"],
  meta: ["meta", "anchor", "accordion", "title2", "title3"],
  anchor: ["anchor"],
  accordion: ["accordion", "title2", "title3"],
  title2: ["title2"],
  title3: ["title3"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicRecorridoCamaraDeComercioDeGuadalajara__ArgProps,
          internalVariantPropNames:
            PlasmicRecorridoCamaraDeComercioDeGuadalajara__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRecorridoCamaraDeComercioDeGuadalajara__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainSection") {
    func.displayName = "PlasmicRecorridoCamaraDeComercioDeGuadalajara";
  } else {
    func.displayName = `PlasmicRecorridoCamaraDeComercioDeGuadalajara.${nodeName}`;
  }
  return func;
}

export const PlasmicRecorridoCamaraDeComercioDeGuadalajara = Object.assign(
  // Top-level PlasmicRecorridoCamaraDeComercioDeGuadalajara renders the root element
  makeNodeComponent("mainSection"),
  {
    // Helper components rendering sub-elements
    mainHeader: makeNodeComponent("mainHeader"),
    mainBanner: makeNodeComponent("mainBanner"),
    banner: makeNodeComponent("banner"),
    description: makeNodeComponent("description"),
    divider: makeNodeComponent("divider"),
    meta: makeNodeComponent("meta"),
    anchor: makeNodeComponent("anchor"),
    accordion: makeNodeComponent("accordion"),
    title2: makeNodeComponent("title2"),
    title3: makeNodeComponent("title3"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicRecorridoCamaraDeComercioDeGuadalajara
    internalVariantProps:
      PlasmicRecorridoCamaraDeComercioDeGuadalajara__VariantProps,
    internalArgProps: PlasmicRecorridoCamaraDeComercioDeGuadalajara__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Recorrido Cámara de Comercio de Guadalajara",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRecorridoCamaraDeComercioDeGuadalajara;
/* prettier-ignore-end */
