// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uEWT1C6ySrjtSMWJntBego
// Component: IQiQ2GDBiFpG
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MainHeader from "../../MainHeader"; // plasmic-import: wtnE0On9QToy/component
import Button2 from "../../Button2"; // plasmic-import: 48nEEeCzck2s/component
import { Anchor } from "inprodi-design-system"; // plasmic-import: ONinya1RhOT2/codeComponent
import { AntdAccordion } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { accordionHelpers as AntdAccordion_Helpers } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { AntdAccordionItem } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import Footer from "../../Footer"; // plasmic-import: Iz_Y_kKZMHTD/component
import { useScreenVariants as useScreenVariantsraGa2MJbEFd } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: RaGa2M-JbEFd/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic.module.css"; // plasmic-import: uEWT1C6ySrjtSMWJntBego/projectcss
import sty from "./PlasmicRecorridoGrupoMexicoTransportes.module.css"; // plasmic-import: IQiQ2GDBiFpG/css

createPlasmicElementProxy;

export const PlasmicRecorridoGrupoMexicoTransportes__VariantProps = new Array();

export const PlasmicRecorridoGrupoMexicoTransportes__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRecorridoGrupoMexicoTransportes__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "accordion.activePanelId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "2",
        onMutate: generateOnMutateForSpec(
          "activePanelId",
          AntdAccordion_Helpers
        )
      },
      {
        path: "mainHeader.menuOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsraGa2MJbEFd()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicRecorridoGrupoMexicoTransportes.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicRecorridoGrupoMexicoTransportes.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicRecorridoGrupoMexicoTransportes.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainSection"}
          data-plasmic-override={overrides.mainSection}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.mainSection
          )}
        >
          <MainHeader
            data-plasmic-name={"mainHeader"}
            data-plasmic-override={overrides.mainHeader}
            className={classNames("__wab_instance", sty.mainHeader)}
            menuOpen={generateStateValueProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
            onMenuOpenChange={generateStateOnChangeProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
          />

          <div
            data-plasmic-name={"mainBanner"}
            data-plasmic-override={overrides.mainBanner}
            className={classNames(projectcss.all, sty.mainBanner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"banner"}
              data-plasmic-override={overrides.banner}
              hasGap={true}
              className={classNames(projectcss.all, sty.banner)}
            />
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"description"}
            data-plasmic-override={overrides.description}
            hasGap={true}
            className={classNames(projectcss.all, sty.description)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__ez0C5)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hqfN2
                )}
              >
                {"Recorridos\nGrupo M\u00e9xico Transportes"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xcKI
                )}
              >
                {
                  "\u201cEl transporte directo destino Tequila para quienes buscan disfrutar su trayecto y libertad en su itinerario.\u201d"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8ER6J
                )}
              >
                {
                  "Descubre Tequila junto a Grupo M\u00e9xico Transportes, la empresa de transporte ferroviario m\u00e1s grande y de mayor cobertura en M\u00e9xico.\n\nEste majestuoso trayecto te permitir\u00e1 descubrir desde el tren la cara m\u00e1s aut\u00e9ntica de Tequila. Complementa tu viaje con una cuidada selecci\u00f3n de alimentos, bebidas y experiencias ofrecidas por Grupo M\u00e9xico, o bien, reserva \u00fanicamente el transporte y avent\u00farate a explorar esta ic\u00f3nica ciudad por tu cuenta."
                }
              </div>
              <Button2
                className={classNames("__wab_instance", sty.button2__yjea5)}
                label={"Reservar"}
              />
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gd9Kz)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___6POd)} />
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uAuM)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__szx9X
                  )}
                >
                  {"Todos los s\u00e1bados.\nAlgunos viernes y domingos."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iPaT
                  )}
                >
                  {
                    "11:00 - 13:00 / Tren GDL-TQL\n13:00 - 13:20 / Autob\u00fas Estaci\u00f3n TQL-TQL Centro\n18:40 - 19:00 / Autob\u00fas TQL Centro-Estaci\u00f3n TQL\n19:00 - 21:00 / Tren TQL-GDL"
                  }
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"divider"}
            data-plasmic-override={overrides.divider}
            hasGap={true}
            className={classNames(projectcss.all, sty.divider)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__q2Kwh)} />
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"meta"}
            data-plasmic-override={overrides.meta}
            hasGap={true}
            className={classNames(projectcss.all, sty.meta)}
          >
            <Anchor
              data-plasmic-name={"anchor"}
              data-plasmic-override={overrides.anchor}
              className={classNames("__wab_instance", sty.anchor)}
              items={[
                { key: "salidas", href: "#salidas", title: "Salidas" },
                { key: "paquetes", href: "#paquetes", title: "Paquetes" },
                {
                  key: "encuentro",
                  href: "#encuentro",
                  title: "Punto de Encuentro"
                },
                {
                  key: "que-llevar",
                  href: "#que-llevar",
                  title: "Qu\u00e9 Llevar"
                },
                {
                  key: "consideraciones",
                  href: "#consideraciones",
                  title: "Consideraciones"
                },
                { key: "reservar", href: "#reservar", title: "Reservar" }
              ]}
              offsetTop={75}
              targetOffset={500}
            />

            <div className={classNames(projectcss.all, sty.freeBox__lsItH)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ab7Z
                )}
              >
                {"Informaci\u00f3n"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sfCYs)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__e2BC)}
                  displayHeight={"54px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"54px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tequila_express/images/group82Jpg.jpg",
                    fullWidth: 108,
                    fullHeight: 108,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__caCfn)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__plH2N
                    )}
                  >
                    {"Operado por Grupo M\u00e9xico Transportes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gBx6
                    )}
                  >
                    {
                      "Elige entre dos categor\u00edas y una variedad de suplementos opcionales para complementar tu viaje y volver cada kil\u00f3metro parte de una historia memorable."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <div
                className={classNames(projectcss.all, sty.freeBox__gzqgm)}
                id={"salidas"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Utt
                  )}
                >
                  {"Salidas"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__d9HEm)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hb7W
                  )}
                >
                  {"Todos los s\u00e1bados, algunos viernes y domingos."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6XUi8
                  )}
                >
                  {
                    "Itinerario:\n11:00 - 13:00 / Tren GDL-TQL\n13:00 - 13:20 / Autob\u00fas Estaci\u00f3n TQL-TQL Centro\n18:40 - 19:00 / Autob\u00fas TQL Centro-Estaci\u00f3n TQL\n19:00 - 21:00 / Tren TQL-GDL"
                  }
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__zGz12)}
                id={"paquetes"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z7ZrM
                  )}
                >
                  {"Paquetes"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__raxqu)}
                />

                {(() => {
                  const child$Props = {
                    activeKey: generateStateValueProp($state, [
                      "accordion",
                      "activePanelId"
                    ]),
                    bordered: true,
                    className: classNames("__wab_instance", sty.accordion),
                    defaultActiveKey: "2",
                    ghost: true,
                    items: (
                      <React.Fragment>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem__qPbqr
                          )}
                          id={1}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mPM1
                              )}
                            >
                              {"Clase Ejecutiva"}
                            </div>
                          }
                          showArrow={false}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__x5Oi2
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__wdUw)}
                              displayHeight={"375px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"40%"}
                              displayWidth={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "100%"
                                  : "40%"
                              }
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/tequila_express/images/rectangle70Jpg.jpg",
                                fullWidth: 846,
                                fullHeight: 756,
                                aspectRatio: undefined
                              }}
                            />

                            <Stack__
                              as={"div"}
                              data-plasmic-name={"title2"}
                              data-plasmic-override={overrides.title2}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.title2)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__fvFm1
                                )}
                              >
                                {"Viaje Sencillo"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__v7Qh
                                )}
                              >
                                {hasVariant(globalVariants, "screen", "medium")
                                  ? "$XXX.00 MXN"
                                  : "$XXX.00 MXN"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___4KuLs
                                )}
                              >
                                <React.Fragment>
                                  <React.Fragment>
                                    {
                                      "La mayor comodidad para viajar con gran espacio entre asientos y una disposici\u00f3n que favorece la convivencia.\n"
                                    }
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__ms79M
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__wwwQm
                                        )}
                                      >
                                        {"Vag\u00f3n Bar"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__lIy6C
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___5Qsjd
                                        )}
                                      >
                                        {"Ventanas panor\u00e1micas"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__q37JN
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__duvgN
                                        )}
                                      >
                                        {"60 asientos"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__th5Mq
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__hdh90
                                        )}
                                      >
                                        {"2 ba\u00f1os\n"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>
                                    {"\nIncluye:\n"}
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul___3GgQf
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__cWbv9
                                        )}
                                      >
                                        {
                                          "Espacio para almacenar una maleta de mano (medidas)\u2026"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__dxy95
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__qetMm
                                        )}
                                      >
                                        {
                                          "Traslado en cami\u00f3n Estaci\u00f3n Tequila - Tequila Centro (ida y vuelta)"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__vh6C
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__s662S
                                        )}
                                      >
                                        {"Seguro de viaje en el transporte"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                </React.Fragment>
                              </div>
                            </Stack__>
                          </Stack__>
                        </AntdAccordionItem>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem__yfsm
                          )}
                          id={"2"}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gYuXs
                              )}
                            >
                              {"Primera Clase"}
                            </div>
                          }
                          showArrow={false}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__thVr
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img___5PqrW)}
                              displayHeight={"375px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"40%"}
                              displayWidth={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "100%"
                                  : "40%"
                              }
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/tequila_express/images/rectangle70Jpg2.jpg",
                                fullWidth: 846,
                                fullHeight: 756,
                                aspectRatio: undefined
                              }}
                            />

                            <Stack__
                              as={"div"}
                              data-plasmic-name={"title3"}
                              data-plasmic-override={overrides.title3}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.title3)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ypqTb
                                )}
                              >
                                {"Viaje Sencillo"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__qpnsX
                                )}
                              >
                                {hasVariant(globalVariants, "screen", "medium")
                                  ? "$XXX.00 MXN"
                                  : "$XXX.00 MXN"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__msFlz
                                )}
                              >
                                <React.Fragment>
                                  <React.Fragment>
                                    {
                                      "La mayor comodidad para viajar con gran espacio entre asientos y una disposici\u00f3n que favorece la convivencia.\n"
                                    }
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__at58G
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__f2Klw
                                        )}
                                      >
                                        {"Vag\u00f3n Bar"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__b9T9V
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__agjVs
                                        )}
                                      >
                                        {"Ventanas panor\u00e1micas"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__did3X
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___74QHe
                                        )}
                                      >
                                        {"60 asientos"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__wYplp
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__po0E6
                                        )}
                                      >
                                        {"2 ba\u00f1os\n"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>
                                    {"\nIncluye:\n"}
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__vxrq8
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___4Ap
                                        )}
                                      >
                                        {
                                          "Espacio para almacenar una maleta de mano (medidas)\u2026"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__eka6E
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___4GRD
                                        )}
                                      >
                                        {
                                          "Traslado en cami\u00f3n Estaci\u00f3n Tequila - Tequila Centro (ida y vuelta)"
                                        }
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__fvuzv
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__ops4V
                                        )}
                                      >
                                        {"Seguro de viaje en el transporte"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                </React.Fragment>
                              </div>
                            </Stack__>
                          </Stack__>
                        </AntdAccordionItem>
                      </React.Fragment>
                    ),

                    onChange: generateStateOnChangePropForCodeComponents(
                      $state,
                      "activePanelId",
                      ["accordion", "activePanelId"],
                      AntdAccordion_Helpers
                    )
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "activePanelId",
                        plasmicStateName: "accordion.activePanelId"
                      }
                    ],

                    [],
                    AntdAccordion_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <AntdAccordion
                      data-plasmic-name={"accordion"}
                      data-plasmic-override={overrides.accordion}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__c1Qx5)}
                id={"encuentro"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pjGhy
                  )}
                >
                  {"Punto de Encuentro"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__mkLoK)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yDgP)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___6ByAb)}
                    displayHeight={"300px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : hasVariant(globalVariants, "screen", "tablet")
                        ? "100%"
                        : "40%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tequila_express/images/imageJpg.jpg",
                      fullWidth: 1224,
                      fullHeight: 504,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ma5KQ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a2KZ1
                      )}
                    >
                      {"Estaci\u00f3n de Ferrocarriles\nMexicanos (Ferromex)"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uw6Cp
                      )}
                    >
                      {"Direcci\u00f3n"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__muMoY
                      )}
                    >
                      {
                        "Av. Circunvalaci\u00f3n Agust\u00edn Y\u00e1\u00f1ez 1009\nModerna\n44910\nGuadalajara, Jal."
                      }
                    </div>
                  </div>
                </Stack__>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__dNogd)}
                id={"que-llevar"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y0Mn
                  )}
                >
                  {"Qu\u00e9 Llevar"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yVM)} />
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__voni5
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__oHkqD
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__zpUHb
                          )}
                        >
                          {"Identificaci\u00f3n oficial"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__m159I
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__kgvfI
                          )}
                        >
                          {"Copia de correo de confirmaci\u00f3n"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__hAwT5
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__jOb8E
                          )}
                        >
                          {"Zapato cerrado y c\u00f3modo"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__hcU9C
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___59Cm9
                          )}
                        >
                          {"Lentes de sol y sombrero"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__cclDp
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__zJmlS
                          )}
                        >
                          {"Ropa c\u00f3moda"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__gBshz
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___6ON4
                          )}
                        >
                          {"Botella de agua"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__prtRa
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___4FdAq
                          )}
                        >
                          {"Protector solar"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__l6O1C)}
                id={"consideraciones"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ev9M5
                  )}
                >
                  {"Consideraciones"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__vyno)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fwMtw
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__l4Nx
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__yyPxj
                          )}
                        >
                          {
                            "Las bebidas y alimentos consumidos en el vag\u00f3n-bar tienen un costo adicional"
                          }
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__wWgWd
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__hTnwi
                          )}
                        >
                          {
                            "Presentarse con una hora de anticipaci\u00f3n para el registro"
                          }
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__ucg40
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___2IgCr
                          )}
                        >
                          {"Itinerarios sujetos a cambios"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__ykIm
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__s0DAg
                          )}
                        >
                          {
                            "Los tiempos de traslados del tren y autob\u00fas son aproximados y sujetos a situaciones ajenas a la empresa"
                          }
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__eqHdB)}
                id={"reservar"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bQ8Iu)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vgcRe)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mwDF
                      )}
                    >
                      {"Inicia el viaje"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m1NKx
                      )}
                    >
                      {
                        "Tequila Express re\u00fane los itinerarios y la oferta diferenciada de los diversos operadores por la ruta del tequila. Al presionar reservar ser\u00e1s redirigido al sitio oficial del operador para completar tu reserva."
                      }
                    </div>
                  </div>
                  <Button2
                    className={classNames(
                      "__wab_instance",
                      sty.button2___4We5K
                    )}
                    label={"Reservar"}
                    light={true}
                  />
                </Stack__>
              </div>
            </div>
          </Stack__>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  mainSection: [
    "mainSection",
    "mainHeader",
    "mainBanner",
    "banner",
    "description",
    "divider",
    "meta",
    "anchor",
    "accordion",
    "title2",
    "title3",
    "footer"
  ],

  mainHeader: ["mainHeader"],
  mainBanner: ["mainBanner", "banner"],
  banner: ["banner"],
  description: ["description"],
  divider: ["divider"],
  meta: ["meta", "anchor", "accordion", "title2", "title3"],
  anchor: ["anchor"],
  accordion: ["accordion", "title2", "title3"],
  title2: ["title2"],
  title3: ["title3"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicRecorridoGrupoMexicoTransportes__ArgProps,
          internalVariantPropNames:
            PlasmicRecorridoGrupoMexicoTransportes__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRecorridoGrupoMexicoTransportes__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainSection") {
    func.displayName = "PlasmicRecorridoGrupoMexicoTransportes";
  } else {
    func.displayName = `PlasmicRecorridoGrupoMexicoTransportes.${nodeName}`;
  }
  return func;
}

export const PlasmicRecorridoGrupoMexicoTransportes = Object.assign(
  // Top-level PlasmicRecorridoGrupoMexicoTransportes renders the root element
  makeNodeComponent("mainSection"),
  {
    // Helper components rendering sub-elements
    mainHeader: makeNodeComponent("mainHeader"),
    mainBanner: makeNodeComponent("mainBanner"),
    banner: makeNodeComponent("banner"),
    description: makeNodeComponent("description"),
    divider: makeNodeComponent("divider"),
    meta: makeNodeComponent("meta"),
    anchor: makeNodeComponent("anchor"),
    accordion: makeNodeComponent("accordion"),
    title2: makeNodeComponent("title2"),
    title3: makeNodeComponent("title3"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicRecorridoGrupoMexicoTransportes
    internalVariantProps: PlasmicRecorridoGrupoMexicoTransportes__VariantProps,
    internalArgProps: PlasmicRecorridoGrupoMexicoTransportes__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Recorrido Grupo México Transportes",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRecorridoGrupoMexicoTransportes;
/* prettier-ignore-end */
