// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uEWT1C6ySrjtSMWJntBego
// Component: 8lN_knEESkxt
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MainHeader from "../../MainHeader"; // plasmic-import: wtnE0On9QToy/component
import Button2 from "../../Button2"; // plasmic-import: 48nEEeCzck2s/component
import { Anchor } from "../../registerAnchor"; // plasmic-import: ONinya1RhOT2/codeComponent
import Footer from "../../Footer"; // plasmic-import: Iz_Y_kKZMHTD/component
import { AntdModal } from "@plasmicpkgs/antd5/skinny/registerModal";
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import { useScreenVariants as useScreenVariantsraGa2MJbEFd } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: RaGa2M-JbEFd/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic.module.css"; // plasmic-import: uEWT1C6ySrjtSMWJntBego/projectcss
import sty from "./PlasmicRecorridoCamaraDeComercioDeGuadalajara.module.css"; // plasmic-import: 8lN_knEESkxt/css
import XSvgIcon from "./icons/PlasmicIcon__XSvg"; // plasmic-import: wbQGNqEUKbny/icon

createPlasmicElementProxy;

export const PlasmicRecorridoCamaraDeComercioDeGuadalajara__VariantProps =
  new Array();

export const PlasmicRecorridoCamaraDeComercioDeGuadalajara__ArgProps =
  new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRecorridoCamaraDeComercioDeGuadalajara__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "mainHeader.menuOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "itineraryModal.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.itineraryModalOpened;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "itineraryModalOpened",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,
        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsraGa2MJbEFd()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicRecorridoCamaraDeComercioDeGuadalajara.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={
            PlasmicRecorridoCamaraDeComercioDeGuadalajara.pageMetadata.title
          }
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={
            PlasmicRecorridoCamaraDeComercioDeGuadalajara.pageMetadata.title
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainSection"}
          data-plasmic-override={overrides.mainSection}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.mainSection
          )}
        >
          <MainHeader
            data-plasmic-name={"mainHeader"}
            data-plasmic-override={overrides.mainHeader}
            className={classNames("__wab_instance", sty.mainHeader)}
            menuOpen={generateStateValueProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
            onMenuOpenChange={generateStateOnChangeProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
          />

          <div
            data-plasmic-name={"mainBanner"}
            data-plasmic-override={overrides.mainBanner}
            className={classNames(projectcss.all, sty.mainBanner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"banner"}
              data-plasmic-override={overrides.banner}
              hasGap={true}
              className={classNames(projectcss.all, sty.banner)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0MGra
                )}
              >
                {""}
              </div>
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"description"}
            data-plasmic-override={overrides.description}
            hasGap={true}
            className={classNames(projectcss.all, sty.description)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__nJAgA)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jyD2E
                )}
              >
                {"Recorridos\nC\u00e1mara de Comercio de Guadalajara"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uesNl
                )}
              >
                {
                  "\u201cLa ruta del tequila en colaboraci\u00f3n con Casa Sauza, donde la cultura y la gastronom\u00eda se entrelazan.\u201d"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__noqZy
                )}
              >
                {
                  "Explora Tequila junto con la C\u00e1mara de Comercio de Guadalajara, una instituci\u00f3n con m\u00e1s de 135 a\u00f1os de historia impulsando el desarrollo econ\u00f3mico y social de la regi\u00f3n.\n\nEste emblem\u00e1tico recorrido te permitir\u00e1 adentrarte en el coraz\u00f3n y la historia del tequila con un viaje a trav\u00e9s de los pintorescos campos de agave. Disfruta la m\u00e1s exquisita cocteler\u00eda y la gastronom\u00eda local, acompa\u00f1ado de un espect\u00e1culo art\u00edstico que captura la esencia de M\u00e9xico y sus tradiciones."
                }
              </div>
              <Button2
                className={classNames("__wab_instance", sty.button2__htEo1)}
                label={"Reservar"}
              />
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tO2FH)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___0U3HY)}
                displayHeight={"40px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"40px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/tequila_express/images/group83Jpg.jpg",
                  fullWidth: 81,
                  fullHeight: 80,
                  aspectRatio: undefined
                }}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zclbr)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8UEOa
                  )}
                >
                  {"Todos los s\u00e1bados."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8JEla
                  )}
                >
                  {"7:00 - 19:45 / Tren GDL-TQL-GDL con experiencia"}
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"divider"}
            data-plasmic-override={overrides.divider}
            hasGap={true}
            className={classNames(projectcss.all, sty.divider)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__sbmwB)} />
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"meta"}
            data-plasmic-override={overrides.meta}
            hasGap={true}
            className={classNames(projectcss.all, sty.meta)}
          >
            <Anchor
              data-plasmic-name={"anchor"}
              data-plasmic-override={overrides.anchor}
              className={classNames("__wab_instance", sty.anchor)}
              items={[
                { key: "salidas", href: "#salidas", title: "Salidas" },
                { key: "paquetes", href: "#paquetes", title: "Paquetes" },
                {
                  key: "encuentro",
                  href: "#encuentro",
                  title: "Punto de Encuentro"
                },
                {
                  key: "que-llevar",
                  href: "#que-llevar",
                  title: "Qu\u00e9 Llevar"
                },
                {
                  key: "consideraciones",
                  href: "#consideraciones",
                  title: "Consideraciones"
                },
                { key: "reservar", href: "#reservar", title: "Reservar" }
              ]}
              offsetTop={75}
              targetOffset={500}
            />

            <div className={classNames(projectcss.all, sty.freeBox__pN69)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pK7Kn
                )}
              >
                {"Informaci\u00f3n"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zzcgb)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__xafW8)}
                  displayHeight={"54px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"54px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tequila_express/images/group82Jpg.jpg",
                    fullWidth: 108,
                    fullHeight: 108,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__acOlW)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kfC7G
                    )}
                  >
                    {"Operado por C\u00e1mara de Comercio de Guadalajara"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h18GL
                    )}
                  >
                    {
                      "Elige entre dos categor\u00edas que te permitir\u00e1n sumergirte en la rica herencia de Tequila con un nivel \u00fanico de estilo."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <div
                className={classNames(projectcss.all, sty.freeBox__hdLoz)}
                id={"salidas"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g2Jw
                  )}
                >
                  {"Salidas"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__avYjZ)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__thhzv
                  )}
                >
                  {"Todos los s\u00e1bados."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e4S
                  )}
                >
                  {
                    "Itinerario:\n7:00 - 19:45 / Tren GDL-TQL-GDL con experiencia"
                  }
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__d55F)}
                id={"paquetes"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jZuu3
                  )}
                >
                  {"Paquetes"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__yXipv)}
                />

                <div
                  data-plasmic-name={"ejecutivo"}
                  data-plasmic-override={overrides.ejecutivo}
                  className={classNames(projectcss.all, sty.ejecutivo)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xiY0X)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ela6A
                      )}
                    >
                      {"Vag\u00f3n Ejecutivo"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___68Kz1
                      )}
                    >
                      {
                        "Del\u00e9itate con la belleza del paisaje agavero mientras disfrutas el servicio de cocteler\u00eda a bordo y vives experiencias inolvidables."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__w4Muq)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nNvnd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yodxE
                        )}
                      >
                        {"Men\u00fa a bordo (ida GDL - TQL):"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r8Epw
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__osQv5
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__zAQyO
                                )}
                              >
                                {"Box Lunch con fruta, jugo y galletas"}
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__e0Exn
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__laMjI
                                )}
                              >
                                {
                                  "Cocteles preparados con Tequila Hornitos\n(blanco, reposado y a\u00f1ejo)"
                                }
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__kpd9H
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__dYyDf
                                )}
                              >
                                {"Cerveza, refrescos y agua natura"}
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wtMmm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__e9XU
                        )}
                      >
                        {"Men\u00fa Quinta Sauza:"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kPll2
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__jiFxq
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__ggkHg
                                )}
                              >
                                {"Entradas: plat\u00f3n de botana mexicana"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__fpuBo
                                )}
                              >
                                {"Buffet a la mesa con 5 guisos"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__h3Avr
                                )}
                              >
                                {"Quesadillas y guarniciones"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li___7VCdX
                                )}
                              >
                                {"Postre a la mesa"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__dpSwG
                                )}
                              >
                                {
                                  "Servicio de tequila, refresco, cerveza, aguas frescas y caf\u00e9"
                                }
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aoTwD)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dw6F
                        )}
                      >
                        {"Men\u00fa a bordo (vuelta TQL - GDL):"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ehtFt
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__wcCgB
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__vkw2T
                                )}
                              >
                                {"Botana salada"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__oLvbz
                                )}
                              >
                                {
                                  "Servicio de tequila, refrescos, cerveza y agua natural"
                                }
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__kL8Hg)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lOk5C
                      )}
                    >
                      {"Traslado redondo con experiencia (GDL - TQL - GDL)"}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___3EtD)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__xqOpN)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "300px"
                            : "100%"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"40%"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "100%"
                            : "40%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tequila_express/images/rectangle70Jpg.jpg",
                          fullWidth: 846,
                          fullHeight: 756,
                          aspectRatio: undefined
                        }}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"title2"}
                        data-plasmic-override={overrides.title2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.title2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oq2Ex
                          )}
                        >
                          {"Viaje redondo GDL - TQL - GDL"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7XsHt
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "medium")
                            ? "$3,400.00 MXN"
                            : "$3,400.00 MXN"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rcd9U
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__ph1Fh
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__gcdr7
                                  )}
                                >
                                  {
                                    "Servicio de estacionamiento en C\u00e1mara de Comercio Guadalajara"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__mfTSd
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__vJD0
                                  )}
                                >
                                  {
                                    "Recepci\u00f3n con Coffee break (galletas y pan dulce)"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__x2IwR
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__lnd0O
                                  )}
                                >
                                  {
                                    "Transportes en autob\u00fas a estaci\u00f3n de tren"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__eyBhF
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li___2C1Uc
                                  )}
                                >
                                  {"Servicios a bordo del tren:"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__cmdqC
                                  )}
                                >
                                  {"Gu\u00eda tur\u00edstico biling\u00fce"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__hOn8J
                                  )}
                                >
                                  {"Servicio de meseros"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__ihjRr
                                  )}
                                >
                                  {"Param\u00e9dico"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__idl6J
                                  )}
                                >
                                  {"Personal de apoyo"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__erKr
                                  )}
                                >
                                  {
                                    "Cocteler\u00eda (seg\u00fan la categor\u00eda)"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__h06J5
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__usfY9
                                  )}
                                >
                                  {"Cantarito de bienvenida en Campos Agaveros"}
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__z7Eni
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__xPlYh
                                  )}
                                >
                                  {"Men\u00fa de comida en Quinta Sauza"}
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul___4J9QA
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__e346
                                  )}
                                >
                                  {
                                    "Espect\u00e1culo \u201cEstampas de M\u00e9xico\u201d"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__hbCmm
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__hkNy
                                  )}
                                >
                                  {
                                    "Visita guiada al centro de Tequila (biling\u00fce)"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bNy6F
                          )}
                          onClick={async event => {
                            const $steps = {};
                            $steps["updateItineraryModalOpened"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["itineraryModalOpened"]
                                    },
                                    operation: 0,
                                    value: true
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;
                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateItineraryModalOpened"] != null &&
                              typeof $steps["updateItineraryModalOpened"] ===
                                "object" &&
                              typeof $steps["updateItineraryModalOpened"]
                                .then === "function"
                            ) {
                              $steps["updateItineraryModalOpened"] =
                                await $steps["updateItineraryModalOpened"];
                            }
                          }}
                        >
                          {"Ver Itinerario"}
                        </div>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </div>
                <div
                  data-plasmic-name={"bar"}
                  data-plasmic-override={overrides.bar}
                  className={classNames(projectcss.all, sty.bar)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___06UX7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ugzp8
                      )}
                    >
                      {"Vag\u00f3n Bar"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9ZPBm
                      )}
                    >
                      {"Exclusivo para mayores de edad"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5OgS4
                      )}
                    >
                      {
                        "Da un upgrade a tu trayecto con un exquisito servicio de mixolog\u00eda a bordo y beneficios exclusivos."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kjlCh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aEqiR)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b2Mmt
                        )}
                      >
                        {"Men\u00fa a bordo (ida GDL - TQL):"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uuG
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul___6Bpfc
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li___04Egz
                                )}
                              >
                                {"Servicio de canap\u00e9s y jugo"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__aVnJ3
                                )}
                              >
                                {"Cata de trufas/borrachitos"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__ricEy
                                )}
                              >
                                {"Mixolog\u00eda a bordo"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__e5QZb
                                )}
                              >
                                {
                                  "Cocteles preparados con Tequila 3 Generaciones (blanco, reposado, a\u00f1ejo)"
                                }
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__rBaE0
                                )}
                              >
                                {"Cerveza, refrescos y agua natural"}
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xvCsp)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7Ghqu
                        )}
                      >
                        {"Men\u00fa Quinta Sauza:"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pVi9O
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__dcte
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__xHa8Q
                                )}
                              >
                                {"Entradas: plat\u00f3n de botana mexicana"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__x16Tj
                                )}
                              >
                                {"Parrillada de cortes con guarniciones"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__w27Xn
                                )}
                              >
                                {"Postre a la mesa"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__brlMl
                                )}
                              >
                                {
                                  "Servicio de tequila, refresco, cerveza, aguas frescas y caf\u00e9"
                                }
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zng9B)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lNfeb
                        )}
                      >
                        {"Men\u00fa a bordo (vuelta TQL - GDL):"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kGhnG
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__vToI
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__fmRH
                                )}
                              >
                                {"Botana selecta"}
                              </li>
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__iq9Nq
                                )}
                              >
                                {
                                  "Servicio de tequila, refrescos, cerveza y agua natural"
                                }
                              </li>
                            </ul>
                          }

                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nQeS)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__u2Nij
                      )}
                    >
                      {"Traslado redondo con experiencia (GDL - TQL - GDL)"}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__yFpoe)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___70Q9Y)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "300px"
                            : "100%"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"40%"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "100%"
                            : "40%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tequila_express/images/rectangle70Jpg.jpg",
                          fullWidth: 846,
                          fullHeight: 756,
                          aspectRatio: undefined
                        }}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"title3"}
                        data-plasmic-override={overrides.title3}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.title3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6Q30C
                          )}
                        >
                          {"Viaje sencillo GDL - TQL"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kynyD
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "medium")
                            ? "$3,900.00 MXN"
                            : "$3,900.00 MXN"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jj1Ip
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "medium")
                            ? "$XXX.00 MXN"
                            : "Solo mayores de edad"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3CScy
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__pyTpT
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__dCp7N
                                  )}
                                >
                                  {
                                    "Servicio de estacionamiento en C\u00e1mara de Comercio Guadalajara"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__rq5Xm
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__norZi
                                  )}
                                >
                                  {
                                    "Recepci\u00f3n con Coffee break (galletas y pan dulce)"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul___5Aoi
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__nhyim
                                  )}
                                >
                                  {
                                    "Transportes en autob\u00fas a estaci\u00f3n de tren"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul___7D7Bc
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li___4N0Xb
                                  )}
                                >
                                  {"Servicios a bordo del tren:"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__r5GVb
                                  )}
                                >
                                  {"Gu\u00eda tur\u00edstico biling\u00fce"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__ymEn
                                  )}
                                >
                                  {"Servicio de meseros"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__wYj7D
                                  )}
                                >
                                  {"Param\u00e9dico"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__z8GSj
                                  )}
                                >
                                  {"Personal de apoyo"}
                                </li>
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__yn2Gm
                                  )}
                                >
                                  {
                                    "Cocteler\u00eda (seg\u00fan la categor\u00eda)"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__iZpIs
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__zkQsn
                                  )}
                                >
                                  {"Cantarito de bienvenida en Campos Agaveros"}
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__ze2Ma
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__lAgYx
                                  )}
                                >
                                  {"Men\u00fa de comida en Quinta Sauza"}
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__qyEQ
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__gr4S
                                  )}
                                >
                                  {
                                    "Espect\u00e1culo \u201cEstampas de M\u00e9xico\u201d"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                            {
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__dChJ
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.li__bpWf
                                  )}
                                >
                                  {
                                    "Visita guiada al centro de Tequila (biling\u00fce)"
                                  }
                                </li>
                              </ul>
                            }

                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ao8V2
                          )}
                          onClick={async event => {
                            const $steps = {};
                            $steps["updateItineraryModalOpened"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["itineraryModalOpened"]
                                    },
                                    operation: 0,
                                    value: true
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;
                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateItineraryModalOpened"] != null &&
                              typeof $steps["updateItineraryModalOpened"] ===
                                "object" &&
                              typeof $steps["updateItineraryModalOpened"]
                                .then === "function"
                            ) {
                              $steps["updateItineraryModalOpened"] =
                                await $steps["updateItineraryModalOpened"];
                            }
                          }}
                        >
                          {"Ver Itinerario"}
                        </div>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__z5Vkv)}
                id={"encuentro"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e48Ua
                  )}
                >
                  {"Punto de Encuentro"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__hYw0)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iFy8N)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hwAy7)}
                    displayHeight={"300px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : hasVariant(globalVariants, "screen", "tablet")
                        ? "100%"
                        : "40%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tequila_express/images/imageJpg2.jpg",
                      fullWidth: 1224,
                      fullHeight: 504,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__cw9SQ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yot5Z
                      )}
                    >
                      {"C\u00e1mara de Comercio de Guadalajara"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h3EO
                      )}
                    >
                      {"Direcci\u00f3n"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__n84ZA
                      )}
                    >
                      {
                        "Av. Ignacio L Vallarta 4085\nCamino Real\n45040\nZapopan, Jal."
                      }
                    </div>
                  </div>
                </Stack__>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__v21RY)}
                id={"que-llevar"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3M9C
                  )}
                >
                  {"Qu\u00e9 Llevar"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__apr8V)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e6IJr
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__vHhb3
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__ivrik
                          )}
                        >
                          {"Identificaci\u00f3n oficial"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__e5CKf
                          )}
                        >
                          {"Copia de correo de confirmaci\u00f3n"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__rdinq
                          )}
                        >
                          {"Zapato cerrado y c\u00f3modo"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__mwpxk
                          )}
                        >
                          {"Lentes de sol y sombrero"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__pNdQd
                          )}
                        >
                          {"Ropa c\u00f3moda"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__fFbU
                          )}
                        >
                          {"Protector solar"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__op3T)}
                id={"consideraciones"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wkKV
                  )}
                >
                  {"Consideraciones"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5HkS)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sFtAs
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__rdfGg
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___5Qivr
                          )}
                        >
                          {
                            "El Vag\u00f3n Bar es exclusivamente para mayores de edad"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___8KlvP
                          )}
                        >
                          {
                            "El viaje en Vag\u00f3n Ejecutivo est\u00e1 disponible para ni\u00f1os a partir de 6 a\u00f1os"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__eumF9
                          )}
                        >
                          {
                            "Presentarse con una hora de anticipaci\u00f3n para su registro"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__iFrH
                          )}
                        >
                          {"Itinerarios sujetos a cambios"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__xgFf
                          )}
                        >
                          {
                            "Los tiempos de traslados del tren y autob\u00fas son aproximados y sujetos a situaciones ajenas a la empresa"
                          }
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__tC2Rt)}
                id={"reservar"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xpZxz)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mz93Y)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jph3A
                      )}
                    >
                      {"Inicia el viaje"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__brDz3
                      )}
                    >
                      {
                        "Tequila Express re\u00fane los itinerarios y la oferta diferenciada de los diversos operadores por la ruta del tequila. Al presionar reservar ser\u00e1s redirigido al sitio oficial del operador para completar tu reserva."
                      }
                    </div>
                  </div>
                  <Button2
                    className={classNames("__wab_instance", sty.button2__lmWa4)}
                    label={"Reservar"}
                    light={true}
                  />
                </Stack__>
              </div>
            </div>
          </Stack__>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />

          <AntdModal
            data-plasmic-name={"itineraryModal"}
            data-plasmic-override={overrides.itineraryModal}
            className={classNames("__wab_instance", sty.itineraryModal)}
            closeIcon={
              <XSvgIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            }
            defaultStylesClassName={classNames(
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              plasmic_antd_5_hostless_css.plasmic_tokens
            )}
            hideFooter={true}
            modalScopeClassName={sty["itineraryModal__modal"]}
            onCancel={async () => {
              const $steps = {};
              $steps["updateItineraryModalOpened"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["itineraryModalOpened"]
                      },
                      operation: 0,
                      value: false
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;
                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateItineraryModalOpened"] != null &&
                typeof $steps["updateItineraryModalOpened"] === "object" &&
                typeof $steps["updateItineraryModalOpened"].then === "function"
              ) {
                $steps["updateItineraryModalOpened"] = await $steps[
                  "updateItineraryModalOpened"
                ];
              }
            }}
            onOpenChange={generateStateOnChangeProp($state, [
              "itineraryModal",
              "open"
            ])}
            open={generateStateValueProp($state, ["itineraryModal", "open"])}
            title={null}
            trigger={null}
            width={
              hasVariant(globalVariants, "screen", "tablet") ? "95%" : "850px"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__khOvw)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qxw0N
                )}
              >
                {"Itinerario"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gq9Y
                )}
              >
                {"Traslado redondo con experiencia (GDL - TQL - GDL)"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wlVal)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9RbRk
                  )}
                >
                  {
                    "7:00 / Recepci\u00f3n en C\u00e1mara de Comercio de Guadalajara\n7:20 / Abordaje y salida en autob\u00fas rumbo a la Estaci\u00f3n de ferrocarril GDL\n8:00 / Salida del tren destino a Tequila\n10:00 / Llegada a Estaci\u00f3n Tequila\n10:15 / Abordaje y salida en autob\u00fas rumbo a Casa Sauza\n10:30 / Llegada a los campos agaveros de Casa Sauza\n\n10:45 / Demostraci\u00f3n de la jima del agave y plantaci\u00f3n\n11:30 / Visita a Bodegas de a\u00f1ejamiento \u201cLa Constancia\u201d de Casa Sauza y degustaci\u00f3n de Tequila Premium\n12:00 / Visita a f\u00e1brica \u201cLa Perseverancia\u201d de Casa Sauza para conocer el proceso de elaboraci\u00f3n del Tequila\n13:15 / Entrega de cantarito de bienvenida\n13:30 / Comida en Quinta Sauza\n14:15 / Espect\u00e1culo \u201cEstampas de M\u00e9xico\u201d\n15:45 / Visita guiada al centro de Tequila\n16:15 / Abordaje y salida en autob\u00fas rumbo Estaci\u00f3n Tequila\n16:30 / Abordaje al tren en Estaci\u00f3n Tequila\n17:00 / Salida del tren destino a Guadalajara\n19:00 / Llegada a Estaci\u00f3n GDL\n19:20 / Abordaje y salida en autob\u00fas rumbo a C\u00e1mara de Comercio de Guadalajara\n19:45 / Llegada a C\u00e1mara de Comercio GDL"
                  }
                </div>
                {(() => {
                  const child$Props = {
                    arrows: false,
                    autoplay: true,
                    autoplaySpeed: 5000,
                    beforeChange: generateStateOnChangePropForCodeComponents(
                      $state,
                      "currentSlide",
                      ["sliderCarousel", "currentSlide"],
                      SliderWrapper_Helpers
                    ),
                    centerMode: false,
                    className: classNames("__wab_instance", sty.sliderCarousel),
                    dots: true,
                    initialSlide: generateStateValueProp($state, [
                      "sliderCarousel",
                      "currentSlide"
                    ]),
                    ref: ref => {
                      $refs["sliderCarousel"] = ref;
                    },
                    sliderScopeClassName: sty["sliderCarousel__slider"]
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "currentSlide",
                        plasmicStateName: "sliderCarousel.currentSlide"
                      }
                    ],

                    [],
                    SliderWrapper_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <SliderWrapper
                      data-plasmic-name={"sliderCarousel"}
                      data-plasmic-override={overrides.sliderCarousel}
                      {...child$Props}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__x3AtC
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__w4Q7X
                          )}
                        >
                          {"Danzas Prehisp\u00e1nicas"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vsg6B
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kLOr
                          )}
                        >
                          {"Ballet Folcl\u00f3rico"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__if0Np
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__usEcL
                          )}
                        >
                          {"Suertes Charras"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___2Ox7Z
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__h9X
                          )}
                        >
                          {"Mariachi en vivo"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__y2Wt6
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___01Xh1
                          )}
                        >
                          {"Cantantes de m\u00fasica vern\u00e1cula"}
                        </div>
                      </div>
                    </SliderWrapper>
                  );
                })()}
              </Stack__>
            </div>
          </AntdModal>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  mainSection: [
    "mainSection",
    "mainHeader",
    "mainBanner",
    "banner",
    "description",
    "divider",
    "meta",
    "anchor",
    "ejecutivo",
    "title2",
    "bar",
    "title3",
    "footer",
    "itineraryModal",
    "sliderCarousel",
    "svg"
  ],

  mainHeader: ["mainHeader"],
  mainBanner: ["mainBanner", "banner"],
  banner: ["banner"],
  description: ["description"],
  divider: ["divider"],
  meta: ["meta", "anchor", "ejecutivo", "title2", "bar", "title3"],
  anchor: ["anchor"],
  ejecutivo: ["ejecutivo", "title2"],
  title2: ["title2"],
  bar: ["bar", "title3"],
  title3: ["title3"],
  footer: ["footer"],
  itineraryModal: ["itineraryModal", "sliderCarousel", "svg"],
  sliderCarousel: ["sliderCarousel"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicRecorridoCamaraDeComercioDeGuadalajara__ArgProps,
          internalVariantPropNames:
            PlasmicRecorridoCamaraDeComercioDeGuadalajara__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRecorridoCamaraDeComercioDeGuadalajara__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainSection") {
    func.displayName = "PlasmicRecorridoCamaraDeComercioDeGuadalajara";
  } else {
    func.displayName = `PlasmicRecorridoCamaraDeComercioDeGuadalajara.${nodeName}`;
  }
  return func;
}

export const PlasmicRecorridoCamaraDeComercioDeGuadalajara = Object.assign(
  // Top-level PlasmicRecorridoCamaraDeComercioDeGuadalajara renders the root element
  makeNodeComponent("mainSection"),
  {
    // Helper components rendering sub-elements
    mainHeader: makeNodeComponent("mainHeader"),
    mainBanner: makeNodeComponent("mainBanner"),
    banner: makeNodeComponent("banner"),
    description: makeNodeComponent("description"),
    divider: makeNodeComponent("divider"),
    meta: makeNodeComponent("meta"),
    anchor: makeNodeComponent("anchor"),
    ejecutivo: makeNodeComponent("ejecutivo"),
    title2: makeNodeComponent("title2"),
    bar: makeNodeComponent("bar"),
    title3: makeNodeComponent("title3"),
    footer: makeNodeComponent("footer"),
    itineraryModal: makeNodeComponent("itineraryModal"),
    sliderCarousel: makeNodeComponent("sliderCarousel"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicRecorridoCamaraDeComercioDeGuadalajara
    internalVariantProps:
      PlasmicRecorridoCamaraDeComercioDeGuadalajara__VariantProps,
    internalArgProps: PlasmicRecorridoCamaraDeComercioDeGuadalajara__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Recorrido Cámara de Comercio de Guadalajara",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRecorridoCamaraDeComercioDeGuadalajara;
/* prettier-ignore-end */
