// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uEWT1C6ySrjtSMWJntBego
// Component: IQiQ2GDBiFpG
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MainHeader from "../../MainHeader"; // plasmic-import: wtnE0On9QToy/component
import Button2 from "../../Button2"; // plasmic-import: 48nEEeCzck2s/component
import { Anchor } from "../../registerAnchor"; // plasmic-import: ONinya1RhOT2/codeComponent
import { AntdAccordion } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { accordionHelpers as AntdAccordion_Helpers } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { AntdAccordionItem } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import Footer from "../../Footer"; // plasmic-import: Iz_Y_kKZMHTD/component
import { AntdModal } from "@plasmicpkgs/antd5/skinny/registerModal";
import { useScreenVariants as useScreenVariantsraGa2MJbEFd } from "../website_starter/PlasmicGlobalVariant__Screen"; // plasmic-import: RaGa2M-JbEFd/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../website_starter/plasmic.module.css"; // plasmic-import: uEWT1C6ySrjtSMWJntBego/projectcss
import sty from "./PlasmicRecorridoGrupoMexicoTransportes.module.css"; // plasmic-import: IQiQ2GDBiFpG/css
import XSvgIcon from "./icons/PlasmicIcon__XSvg"; // plasmic-import: wbQGNqEUKbny/icon

createPlasmicElementProxy;

export const PlasmicRecorridoGrupoMexicoTransportes__VariantProps = new Array();

export const PlasmicRecorridoGrupoMexicoTransportes__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRecorridoGrupoMexicoTransportes__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "accordion.activePanelId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "1",
        onMutate: generateOnMutateForSpec(
          "activePanelId",
          AntdAccordion_Helpers
        )
      },
      {
        path: "mainHeader.menuOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "bookingModal.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return (() => {
                return $state.bookingModalOpened;
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "bookingModalOpened",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsraGa2MJbEFd()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicRecorridoGrupoMexicoTransportes.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicRecorridoGrupoMexicoTransportes.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicRecorridoGrupoMexicoTransportes.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"mainSection"}
          data-plasmic-override={overrides.mainSection}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.mainSection
          )}
        >
          <MainHeader
            data-plasmic-name={"mainHeader"}
            data-plasmic-override={overrides.mainHeader}
            className={classNames("__wab_instance", sty.mainHeader)}
            menuOpen={generateStateValueProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
            onMenuOpenChange={generateStateOnChangeProp($state, [
              "mainHeader",
              "menuOpen"
            ])}
          />

          <div
            data-plasmic-name={"mainBanner"}
            data-plasmic-override={overrides.mainBanner}
            className={classNames(projectcss.all, sty.mainBanner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"banner"}
              data-plasmic-override={overrides.banner}
              hasGap={true}
              className={classNames(projectcss.all, sty.banner)}
            />
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"description"}
            data-plasmic-override={overrides.description}
            hasGap={true}
            className={classNames(projectcss.all, sty.description)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__ez0C5)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hqfN2
                )}
              >
                {"Recorridos\nGrupo M\u00e9xico Transportes"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xcKI
                )}
              >
                {
                  "\u201cEl transporte directo destino Tequila para quienes buscan disfrutar su trayecto y libertad en su itinerario.\u201d"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8ER6J
                )}
              >
                {
                  "Descubre Tequila junto a Grupo M\u00e9xico Transportes, la empresa de transporte ferroviario m\u00e1s grande y de mayor cobertura en M\u00e9xico.\n\nEste majestuoso trayecto te permitir\u00e1 descubrir desde el tren la cara m\u00e1s aut\u00e9ntica de Tequila. Complementa tu viaje con una cuidada selecci\u00f3n de alimentos, bebidas y experiencias ofrecidas por Grupo M\u00e9xico, o bien, reserva \u00fanicamente el transporte y avent\u00farate a explorar esta ic\u00f3nica ciudad por tu cuenta."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vXo6
                )}
              >
                {
                  "Complementa tu viaje con las diferentes opciones de alimentos y bebidas, o con las experiencias y alojamientos ofrecidas por Grupo M\u00e9xico Transportes."
                }
              </div>
              <Button2
                className={classNames("__wab_instance", sty.button2__yjea5)}
                label={"Reservar"}
                onClick={async () => {
                  const $steps = {};
                  $steps["updateBookingModalOpened"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["bookingModalOpened"]
                          },
                          operation: 0,
                          value: true
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;
                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateBookingModalOpened"] != null &&
                    typeof $steps["updateBookingModalOpened"] === "object" &&
                    typeof $steps["updateBookingModalOpened"].then ===
                      "function"
                  ) {
                    $steps["updateBookingModalOpened"] = await $steps[
                      "updateBookingModalOpened"
                    ];
                  }
                }}
              />
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gd9Kz)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zc7I)}
                displayHeight={"40px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"40px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/tequila_express/images/group83Jpg.jpg",
                  fullWidth: 81,
                  fullHeight: 80,
                  aspectRatio: undefined
                }}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uAuM)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__szx9X
                  )}
                >
                  {"Todos los viernes, s\u00e1bados y domingos"}
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"divider"}
            data-plasmic-override={overrides.divider}
            hasGap={true}
            className={classNames(projectcss.all, sty.divider)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__q2Kwh)} />
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"meta"}
            data-plasmic-override={overrides.meta}
            hasGap={true}
            className={classNames(projectcss.all, sty.meta)}
          >
            <Anchor
              data-plasmic-name={"anchor"}
              data-plasmic-override={overrides.anchor}
              className={classNames("__wab_instance", sty.anchor)}
              items={[
                { key: "salidas", href: "#salidas", title: "Salidas" },
                { key: "paquetes", href: "#paquetes", title: "Paquetes" },
                {
                  key: "encuentro",
                  href: "#encuentro",
                  title: "Punto de Encuentro"
                },
                {
                  key: "que-llevar",
                  href: "#que-llevar",
                  title: "Qu\u00e9 Llevar"
                },
                {
                  key: "consideraciones",
                  href: "#consideraciones",
                  title: "Consideraciones"
                },
                { key: "reservar", href: "#reservar", title: "Reservar" }
              ]}
              offsetTop={100}
              targetOffset={500}
            />

            <div className={classNames(projectcss.all, sty.freeBox__lsItH)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ab7Z
                )}
              >
                {"Informaci\u00f3n"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sfCYs)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__e2BC)}
                  displayHeight={"54px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"54px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tequila_express/images/group82Jpg.jpg",
                    fullWidth: 108,
                    fullHeight: 108,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__caCfn)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__plH2N
                    )}
                  >
                    {"Operado por Grupo M\u00e9xico Transportes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gBx6
                    )}
                  >
                    {
                      "Elige entre dos categor\u00edas y una variedad de suplementos opcionales para complementar tu viaje y volver cada kil\u00f3metro parte de una historia memorable."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <div
                className={classNames(projectcss.all, sty.freeBox__gzqgm)}
                id={"salidas"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Utt
                  )}
                >
                  {"Salidas"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__d9HEm)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hb7W
                  )}
                >
                  {"Todos los viernes, s\u00e1bados y domingos."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6XUi8
                  )}
                >
                  {"Itinerario:"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__sqt0E)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qxSxE
                    )}
                  >
                    {"Viernes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ms4Hc
                    )}
                  >
                    {
                      "Salida 10:00 / Llegada a las 12:00\nRegreso 19:00 / Llegada 21:00"
                    }
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___08AqD)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y23Q3
                    )}
                  >
                    {"S\u00e1bado"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mhCXo
                    )}
                  >
                    {
                      "Salida 10:30 / Llegada a las 12:30\nRegreso 19:00 / Llegada 21:00"
                    }
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___2IJpl)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ig8Qx
                    )}
                  >
                    {"Domingo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oaF
                    )}
                  >
                    {
                      "Salida 10:00 / Llegada a las 12:00\nRegreso 17:30 / Llegada 19:30"
                    }
                  </div>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__zGz12)}
                id={"paquetes"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z7ZrM
                  )}
                >
                  {"Paquetes"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__raxqu)}
                />

                {(() => {
                  const child$Props = {
                    activeKey: generateStateValueProp($state, [
                      "accordion",
                      "activePanelId"
                    ]),
                    bordered: true,
                    className: classNames("__wab_instance", sty.accordion),
                    defaultActiveKey: "1",
                    ghost: true,
                    items: (
                      <React.Fragment>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem__qPbqr
                          )}
                          id={1}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mPM1
                              )}
                            >
                              {"Clase Ejecutiva"}
                            </div>
                          }
                          showArrow={false}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__x5Oi2
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__wdUw)}
                              displayHeight={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "350px"
                                  : "100%"
                              }
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"40%"}
                              displayWidth={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "100%"
                                  : "40%"
                              }
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/tequila_express/images/rectangle70Jpg.jpg",
                                fullWidth: 846,
                                fullHeight: 756,
                                aspectRatio: undefined
                              }}
                            />

                            <Stack__
                              as={"div"}
                              data-plasmic-name={"title2"}
                              data-plasmic-override={overrides.title2}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.title2)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___8LCyI
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__wnDY
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__fvFm1
                                    )}
                                  >
                                    {"Viaje Sencillo"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__v7Qh
                                    )}
                                  >
                                    {hasVariant(
                                      globalVariants,
                                      "screen",
                                      "medium"
                                    )
                                      ? "$1,150.00 MXN"
                                      : "$1,150.00 MXN"}
                                  </div>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__h1Ota
                                  )}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__zXhMj
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__pqZaE
                                    )}
                                  >
                                    {"Viaje Redondo"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__bziq
                                    )}
                                  >
                                    {hasVariant(
                                      globalVariants,
                                      "screen",
                                      "medium"
                                    )
                                      ? "$1,785.00 MXN"
                                      : "$1,785.00 MXN"}
                                  </div>
                                </div>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___4KuLs
                                )}
                              >
                                <React.Fragment>
                                  <React.Fragment>
                                    {
                                      "La mayor comodidad para viajar con gran espacio entre asientos y una disposici\u00f3n que favorece la convivencia.\n\n"
                                    }
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__mqYbk
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__h5WLh
                                        )}
                                      >
                                        {"Ventanas panor\u00e1micas"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__qysMa
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__w27VR
                                        )}
                                      >
                                        {"60 asientos"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul___4Ueub
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__l6LpR
                                        )}
                                      >
                                        {"2 ba\u00f1os"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>
                                    {"\nIncluye:\n"}
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__l35Hp
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__ly4UY
                                        )}
                                      >
                                        {"Seguro de viaje en el transporte"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                </React.Fragment>
                              </div>
                            </Stack__>
                          </Stack__>
                        </AntdAccordionItem>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem__yfsm
                          )}
                          id={"2"}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gYuXs
                              )}
                            >
                              {"Primera Clase"}
                            </div>
                          }
                          showArrow={false}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__thVr
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img___5PqrW)}
                              displayHeight={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "350px"
                                  : "100%"
                              }
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"40%"}
                              displayWidth={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "100%"
                                  : "40%"
                              }
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/tequila_express/images/rectangle70Jpg2.jpg",
                                fullWidth: 846,
                                fullHeight: 756,
                                aspectRatio: undefined
                              }}
                            />

                            <Stack__
                              as={"div"}
                              data-plasmic-name={"title3"}
                              data-plasmic-override={overrides.title3}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.title3)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__ikWic
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__uA1SK
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__vtd8E
                                    )}
                                  >
                                    {"Viaje Sencillo"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__nAfDs
                                    )}
                                  >
                                    {hasVariant(
                                      globalVariants,
                                      "screen",
                                      "medium"
                                    )
                                      ? "$1,400.00 MXN"
                                      : "$1,400.00 MXN"}
                                  </div>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__e5ITd
                                  )}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__nyNg0
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__ipXeJ
                                    )}
                                  >
                                    {"Viaje Redondo"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___3QWot
                                    )}
                                  >
                                    {hasVariant(
                                      globalVariants,
                                      "screen",
                                      "medium"
                                    )
                                      ? "$2,200.00 MXN"
                                      : "$2,200.00 MXN"}
                                  </div>
                                </div>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__msFlz
                                )}
                              >
                                <React.Fragment>
                                  <React.Fragment>
                                    {
                                      "La mayor comodidad para viajar con gran espacio entre asientos y una disposici\u00f3n que favorece la convivencia.\n\n"
                                    }
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__c7HPx
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__xdv7U
                                        )}
                                      >
                                        {"Bar dentro de vag\u00f3n"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__cscht
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__w1UzL
                                        )}
                                      >
                                        {"Incluye el acceso al vag\u00f3n Bar"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__qc13C
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__nbzo
                                        )}
                                      >
                                        {"Ventanas panor\u00e1micas"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__bDlR
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__nw16I
                                        )}
                                      >
                                        {"52 asientos"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__nDAnc
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li__wcu3W
                                        )}
                                      >
                                        {"2 ba\u00f1os"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>
                                    {"\nIncluye:\n"}
                                  </React.Fragment>
                                  {
                                    <ul
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.ul,
                                        sty.ul__kUjhX
                                      )}
                                    >
                                      <li
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.li,
                                          projectcss.__wab_text,
                                          sty.li___9DffV
                                        )}
                                      >
                                        {"Seguro de viaje en el transporte"}
                                      </li>
                                    </ul>
                                  }

                                  <React.Fragment>{""}</React.Fragment>
                                </React.Fragment>
                              </div>
                            </Stack__>
                          </Stack__>
                        </AntdAccordionItem>
                      </React.Fragment>
                    ),

                    onChange: generateStateOnChangePropForCodeComponents(
                      $state,
                      "activePanelId",
                      ["accordion", "activePanelId"],
                      AntdAccordion_Helpers
                    )
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "activePanelId",
                        plasmicStateName: "accordion.activePanelId"
                      }
                    ],

                    [],
                    AntdAccordion_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <AntdAccordion
                      data-plasmic-name={"accordion"}
                      data-plasmic-override={overrides.accordion}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__c1Qx5)}
                id={"encuentro"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pjGhy
                  )}
                >
                  {"Punto de Encuentro"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__mkLoK)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yDgP)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___6ByAb)}
                    displayHeight={"300px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : hasVariant(globalVariants, "screen", "tablet")
                        ? "100%"
                        : "40%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tequila_express/images/imageJpg.jpg",
                      fullWidth: 1224,
                      fullHeight: 504,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ma5KQ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a2KZ1
                      )}
                    >
                      {"Estaci\u00f3n Ferromex"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y9JFb
                      )}
                    >
                      {"No cuenta con estacionamiento"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uw6Cp
                      )}
                    >
                      {"Direcci\u00f3n"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__muMoY
                      )}
                    >
                      {
                        "Av. Circunvalaci\u00f3n Agust\u00edn Y\u00e1\u00f1ez 1009\nModerna\n44910\nGuadalajara, Jal."
                      }
                    </div>
                  </div>
                </Stack__>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__dNogd)}
                id={"que-llevar"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y0Mn
                  )}
                >
                  {"Qu\u00e9 Llevar"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yVM)} />
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__voni5
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__oHkqD
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__zpUHb
                          )}
                        >
                          {"Identificaci\u00f3n oficial"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__m159I
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__kgvfI
                          )}
                        >
                          {"Copia de correo de confirmaci\u00f3n"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__hAwT5
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__jOb8E
                          )}
                        >
                          {"Zapato cerrado y c\u00f3modo"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__hcU9C
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___59Cm9
                          )}
                        >
                          {"Lentes de sol y sombrero/gorra"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__cclDp
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__zJmlS
                          )}
                        >
                          {"Ropa c\u00f3moda"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__gBshz
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___6ON4
                          )}
                        >
                          {"Botella de agua"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__prtRa
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___4FdAq
                          )}
                        >
                          {"Protector solar"}
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__l6O1C)}
                id={"consideraciones"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ev9M5
                  )}
                >
                  {"Consideraciones"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__vyno)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fwMtw
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__l4Nx
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__yyPxj
                          )}
                        >
                          {
                            "Presentarse con una hora de anticipaci\u00f3n para el registro"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__s8VTy
                          )}
                        >
                          {"Itinerarios sujetos a cambios"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__cocoQ
                          )}
                        >
                          {
                            "Los tiempos de traslados del tren y autob\u00fas son aproximados y sujetos a situaciones ajenas a la empresa"
                          }
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__sMaEn
                          )}
                        >
                          {
                            "No contamos con estacionamiento, sugerimos llegar en taxi o servicio de transporte de plataforma digital"
                          }
                        </li>
                      </ul>
                    }

                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__eqHdB)}
                id={"reservar"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bQ8Iu)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vgcRe)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mwDF
                      )}
                    >
                      {"Inicia el viaje"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m1NKx
                      )}
                    >
                      {
                        "Tequila Express re\u00fane los itinerarios y la oferta diferenciada de los diversos operadores por la ruta del tequila. Al presionar reservar ser\u00e1s redirigido al sitio oficial del operador para completar tu reserva."
                      }
                    </div>
                  </div>
                  <Button2
                    className={classNames(
                      "__wab_instance",
                      sty.button2___4We5K
                    )}
                    label={"Reservar"}
                    light={true}
                    onClick={async () => {
                      const $steps = {};
                      $steps["updateBookingModalOpened"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["bookingModalOpened"]
                              },
                              operation: 0,
                              value: true
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;
                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateBookingModalOpened"] != null &&
                        typeof $steps["updateBookingModalOpened"] ===
                          "object" &&
                        typeof $steps["updateBookingModalOpened"].then ===
                          "function"
                      ) {
                        $steps["updateBookingModalOpened"] = await $steps[
                          "updateBookingModalOpened"
                        ];
                      }
                    }}
                  />
                </Stack__>
              </div>
            </div>
          </Stack__>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />

          <AntdModal
            data-plasmic-name={"bookingModal"}
            data-plasmic-override={overrides.bookingModal}
            className={classNames("__wab_instance", sty.bookingModal)}
            closeIcon={
              <XSvgIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            }
            defaultStylesClassName={classNames(
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              plasmic_antd_5_hostless_css.plasmic_tokens
            )}
            hideFooter={true}
            modalScopeClassName={sty["bookingModal__modal"]}
            onCancel={async () => {
              const $steps = {};
              $steps["updateBookingModalOpened"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["bookingModalOpened"]
                      },
                      operation: 0,
                      value: false
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;
                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateBookingModalOpened"] != null &&
                typeof $steps["updateBookingModalOpened"] === "object" &&
                typeof $steps["updateBookingModalOpened"].then === "function"
              ) {
                $steps["updateBookingModalOpened"] = await $steps[
                  "updateBookingModalOpened"
                ];
              }
            }}
            onOpenChange={generateStateOnChangeProp($state, [
              "bookingModal",
              "open"
            ])}
            open={generateStateValueProp($state, ["bookingModal", "open"])}
            title={null}
            trigger={null}
            width={
              hasVariant(globalVariants, "screen", "tablet") ? "95%" : "600px"
            }
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__e5C0M)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"lazy"}
              src={{
                src: "/plasmic/tequila_express/images/imagenDeWhatsApp20240913ALas1329440B7C32481Jpg.jpg",
                fullWidth: 3200,
                fullHeight: 2132,
                aspectRatio: undefined
              }}
            />
          </AntdModal>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  mainSection: [
    "mainSection",
    "mainHeader",
    "mainBanner",
    "banner",
    "description",
    "divider",
    "meta",
    "anchor",
    "accordion",
    "title2",
    "title3",
    "footer",
    "bookingModal",
    "svg"
  ],

  mainHeader: ["mainHeader"],
  mainBanner: ["mainBanner", "banner"],
  banner: ["banner"],
  description: ["description"],
  divider: ["divider"],
  meta: ["meta", "anchor", "accordion", "title2", "title3"],
  anchor: ["anchor"],
  accordion: ["accordion", "title2", "title3"],
  title2: ["title2"],
  title3: ["title3"],
  footer: ["footer"],
  bookingModal: ["bookingModal", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicRecorridoGrupoMexicoTransportes__ArgProps,
          internalVariantPropNames:
            PlasmicRecorridoGrupoMexicoTransportes__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRecorridoGrupoMexicoTransportes__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mainSection") {
    func.displayName = "PlasmicRecorridoGrupoMexicoTransportes";
  } else {
    func.displayName = `PlasmicRecorridoGrupoMexicoTransportes.${nodeName}`;
  }
  return func;
}

export const PlasmicRecorridoGrupoMexicoTransportes = Object.assign(
  // Top-level PlasmicRecorridoGrupoMexicoTransportes renders the root element
  makeNodeComponent("mainSection"),
  {
    // Helper components rendering sub-elements
    mainHeader: makeNodeComponent("mainHeader"),
    mainBanner: makeNodeComponent("mainBanner"),
    banner: makeNodeComponent("banner"),
    description: makeNodeComponent("description"),
    divider: makeNodeComponent("divider"),
    meta: makeNodeComponent("meta"),
    anchor: makeNodeComponent("anchor"),
    accordion: makeNodeComponent("accordion"),
    title2: makeNodeComponent("title2"),
    title3: makeNodeComponent("title3"),
    footer: makeNodeComponent("footer"),
    bookingModal: makeNodeComponent("bookingModal"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicRecorridoGrupoMexicoTransportes
    internalVariantProps: PlasmicRecorridoGrupoMexicoTransportes__VariantProps,
    internalArgProps: PlasmicRecorridoGrupoMexicoTransportes__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Recorrido Grupo México Transportes",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRecorridoGrupoMexicoTransportes;
/* prettier-ignore-end */
